# -*- coding: utf-8 -*-
"""OchoaJonathan_HPC_S4C1Casa1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-cBqLpl5AQTnNKenqK19-JJmkCYQbl2
"""

import numpy as np
import matplotlib.pylab as plt


datos=np.genfromtxt("datos1.dat")

plt.figure()
plt.plot(datos[:,0],datos[:,1])
plt.savefig("err_derC.pdf")